//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Br.Com.BiscoitinhosVovoLiva.Intranet.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Mensagens {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensagens() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Br.Com.BiscoitinhosVovoLiva.Intranet.App_LocalResources.Mensagens", typeof(Mensagens).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail inválido..
        /// </summary>
        internal static string ERRO_EMAIL_INVALIDO {
            get {
                return ResourceManager.GetString("ERRO_EMAIL_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao enviar e-mail..
        /// </summary>
        internal static string ERRO_ENVIAR_EMAIL {
            get {
                return ResourceManager.GetString("ERRO_ENVIAR_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro inesperado..
        /// </summary>
        internal static string ERRO_MSG_PADRAO {
            get {
                return ResourceManager.GetString("ERRO_MSG_PADRAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você já realizou seu pedido! Caso queira alterá-lo, clique em Atualizar Pedido..
        /// </summary>
        internal static string ERRO_PEDIDO_EXISTENTE {
            get {
                return ResourceManager.GetString("ERRO_PEDIDO_EXISTENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seu pedido não foi encontrado para atualização. Realize o pedido primeiro..
        /// </summary>
        internal static string ERRO_PEDIDO_NAO_ENCONTRADO {
            get {
                return ResourceManager.GetString("ERRO_PEDIDO_NAO_ENCONTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desculpe mas quantidade de pães de queijo deve ser no minimo 1 e no máximo 2..
        /// </summary>
        internal static string ERRO_QTDADE_INVALIDA {
            get {
                return ResourceManager.GetString("ERRO_QTDADE_INVALIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao recuperar os dados do formulário..
        /// </summary>
        internal static string ERRO_REQ_FORM_COLLECTION {
            get {
                return ResourceManager.GetString("ERRO_REQ_FORM_COLLECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário não encontrado..
        /// </summary>
        internal static string ERRO_USUARIO_NAO_ENCONTRADO {
            get {
                return ResourceManager.GetString("ERRO_USUARIO_NAO_ENCONTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;Olá {0},&lt;/h3&gt;&lt;br /&gt;Seu pedido foi atualizado com sucesso!&lt;br /&gt;Agora você receberá &lt;b&gt;{1}&lt;/b&gt; {2} de queijo.&lt;br /&gt;&lt;br /&gt;Obrigado por atualizar seu pedido e até sexta!&lt;br /&gt;&lt;br /&gt;Att,&lt;br /&gt;André Bacaglini&lt;br /&gt;{3}.
        /// </summary>
        internal static string SUCESSO_EMAIL_ATUALIZAR {
            get {
                return ResourceManager.GetString("SUCESSO_EMAIL_ATUALIZAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;Olá {0},&lt;/h3&gt;&lt;br /&gt;Seu pedido foi realizado com sucesso!&lt;br /&gt;Você pediu &lt;b&gt;{1}&lt;/b&gt; {2} de queijo.&lt;br /&gt;&lt;br /&gt;Obrigado por realizar seu pedido e até sexta!&lt;br /&gt;&lt;br /&gt;Att,&lt;br /&gt;André Bacaglini&lt;br /&gt;{3}.
        /// </summary>
        internal static string SUCESSO_EMAIL_REALIZAR {
            get {
                return ResourceManager.GetString("SUCESSO_EMAIL_REALIZAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seu pedido foi atualizado com sucesso!.
        /// </summary>
        internal static string SUCESSO_PEDIDO_ATUALIZADO {
            get {
                return ResourceManager.GetString("SUCESSO_PEDIDO_ATUALIZADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seu pedido foi realizado com sucesso!.
        /// </summary>
        internal static string SUCESSO_PEDIDO_REALIZADO {
            get {
                return ResourceManager.GetString("SUCESSO_PEDIDO_REALIZADO", resourceCulture);
            }
        }
    }
}
